In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent))

%load_ext autoreload
%autoreload 2

import pandas as pd
from IPython.display import display

from db.connection import get_session
from evaluation.recall import evaluate_recall, load_ground_truth, dataset_stats
from evaluation.mlflow_log import log_eval_to_mlflow
from similarity.weights import SimilarityWeights

# --- Config: change these and re-run to compare ---
WEIGHTS = SimilarityWeights()  # uses defaults from config
TOP_K = 5

In [2]:
session = get_session()
pairs = load_ground_truth(session)
print(f"{len(pairs)} ground truth pairs loaded ({len(pairs) * 2} bidirectional evaluations)")

result = evaluate_recall(session, pairs, weights=WEIGHTS, top_k=TOP_K)
print(f"Evaluation complete in {result.duration_s}s")

2026-03-06 17:54:17,572 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2026-03-06 17:54:17,573 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-03-06 17:54:17,577 INFO sqlalchemy.engine.Engine select current_schema()
2026-03-06 17:54:17,577 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-03-06 17:54:17,580 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2026-03-06 17:54:17,580 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-03-06 17:54:17,581 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-03-06 17:54:17,583 INFO sqlalchemy.engine.Engine SELECT ground_truth_pairs.id AS ground_truth_pairs_id, ground_truth_pairs.species_a AS ground_truth_pairs_species_a, ground_truth_pairs.species_b AS ground_truth_pairs_species_b, ground_truth_pairs.danger_note AS ground_truth_pairs_danger_note, ground_truth_pairs.source AS ground_truth_pairs_source, ground_truth_pairs.notes AS ground_truth_pairs_notes
FROM ground_truth_pairs
2026-03-06 17:54:17,584 INFO sqlalchemy.engine.Engine [generated in 0.00037s] {}
31 ground truth pairs loaded (62 bidirectional evaluations)
2026-03-06 17:54:17,591 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.scientific_name ILIKE %(scientific_name_1)s
 LIMIT %(param_1)s
2026-03-06 17:54:17,592 INFO sqlalchemy.engine.Engine [generated in 0.00204s] {'scientific_name_1': 'Amanita caesarea', 'param_1': 1}
2026-03-06 17:54:17,613 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_macro_visual <=> q.embedding_macro_visual) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_macro_visual FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_macro_visual IS NOT NULL
          AND q.embedding_macro_visual IS NOT NULL
        ORDER BY rs.embedding_macro_visual <=> q.embedding_macro_visual
        LIMIT %(top_k)s

2026-03-06 17:54:17,613 INFO sqlalchemy.engine.Engine [generated in 0.00043s] {'species_id': 165, 'top_k': 60}
2026-03-06 17:54:17,618 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_structural <=> q.embedding_structural) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_structural FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_structural IS NOT NULL
          AND q.embedding_structural IS NOT NULL
        ORDER BY rs.embedding_structural <=> q.embedding_structural
        LIMIT %(top_k)s

2026-03-06 17:54:17,618 INFO sqlalchemy.engine.Engine [generated in 0.00040s] {'species_id': 165, 'top_k': 60}
2026-03-06 17:54:17,620 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_flesh_sensory <=> q.embedding_flesh_sensory) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_flesh_sensory FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_flesh_sensory IS NOT NULL
          AND q.embedding_flesh_sensory IS NOT NULL
        ORDER BY rs.embedding_flesh_sensory <=> q.embedding_flesh_sensory
        LIMIT %(top_k)s

2026-03-06 17:54:17,621 INFO sqlalchemy.engine.Engine [generated in 0.00037s] {'species_id': 165, 'top_k': 60}
2026-03-06 17:54:17,629 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_microscopic_lab <=> q.embedding_microscopic_lab) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_microscopic_lab FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_microscopic_lab IS NOT NULL
          AND q.embedding_microscopic_lab IS NOT NULL
        ORDER BY rs.embedding_microscopic_lab <=> q.embedding_microscopic_lab
        LIMIT %(top_k)s

2026-03-06 17:54:17,631 INFO sqlalchemy.engine.Engine [generated in 0.00260s] {'species_id': 165, 'top_k': 60}
2026-03-06 17:54:17,634 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_ecological <=> q.embedding_ecological) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_ecological FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_ecological IS NOT NULL
          AND q.embedding_ecological IS NOT NULL
        ORDER BY rs.embedding_ecological <=> q.embedding_ecological
        LIMIT %(top_k)s

2026-03-06 17:54:17,635 INFO sqlalchemy.engine.Engine [generated in 0.00104s] {'species_id': 165, 'top_k': 60}
2026-03-06 17:54:17,640 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_taxonomic <=> q.embedding_taxonomic) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_taxonomic FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_taxonomic IS NOT NULL
          AND q.embedding_taxonomic IS NOT NULL
        ORDER BY rs.embedding_taxonomic <=> q.embedding_taxonomic
        LIMIT %(top_k)s

2026-03-06 17:54:17,640 INFO sqlalchemy.engine.Engine [generated in 0.00043s] {'species_id': 165, 'top_k': 60}
2026-03-06 17:54:17,643 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:54:17,643 INFO sqlalchemy.engine.Engine [generated in 0.00044s] {'pk_1': 117}
2026-03-06 17:54:17,647 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:54:17,647 INFO sqlalchemy.engine.Engine [cached since 0.004851s ago] {'pk_1': 118}
2026-03-06 17:54:17,651 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:54:17,652 INFO sqlalchemy.engine.Engine [cached since 0.009238s ago] {'pk_1': 119}
2026-03-06 17:54:17,655 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:54:17,655 INFO sqlalchemy.engine.Engine [cached since 0.01261s ago] {'pk_1': 120}
2026-03-06 17:54:17,659 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:54:17,659 INFO sqlalchemy.engine.Engine [cached since 0.01674s ago] {'pk_1': 121}
2026-03-06 17:54:17,662 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:54:17,662 INFO sqlalchemy.engine.Engine [cached since 0.01966s ago] {'pk_1': 122}

Error querying Cortinarius Seriocybe: Species not found: 'Cortinarius Seriocybe'

2026-03-06 17:54:59,460 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.scientific_name ILIKE %(scientific_name_1)s
 LIMIT %(param_1)s
2026-03-06 17:54:59,461 INFO sqlalchemy.engine.Engine [cached since 41.87s ago] {'scientific_name_1': 'Cortinarius Violaceus', 'param_1': 1}
2026-03-06 17:54:59,483 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_macro_visual <=> q.embedding_macro_visual) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_macro_visual FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_macro_visual IS NOT NULL
          AND q.embedding_macro_visual IS NOT NULL
        ORDER BY rs.embedding_macro_visual <=> q.embedding_macro_visual
        LIMIT %(top_k)s

2026-03-06 17:54:59,488 INFO sqlalchemy.engine.Engine [cached since 41.88s ago] {'species_id': 129, 'top_k': 60}
2026-03-06 17:54:59,492 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_structural <=> q.embedding_structural) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_structural FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_structural IS NOT NULL
          AND q.embedding_structural IS NOT NULL
        ORDER BY rs.embedding_structural <=> q.embedding_structural
        LIMIT %(top_k)s

2026-03-06 17:54:59,493 INFO sqlalchemy.engine.Engine [cached since 41.88s ago] {'species_id': 129, 'top_k': 60}
2026-03-06 17:54:59,496 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_flesh_sensory <=> q.embedding_flesh_sensory) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_flesh_sensory FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_flesh_sensory IS NOT NULL
          AND q.embedding_flesh_sensory IS NOT NULL
        ORDER BY rs.embedding_flesh_sensory <=> q.embedding_flesh_sensory
        LIMIT %(top_k)s

2026-03-06 17:54:59,496 INFO sqlalchemy.engine.Engine [cached since 41.88s ago] {'species_id': 129, 'top_k': 60}
2026-03-06 17:54:59,500 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_microscopic_lab <=> q.embedding_microscopic_lab) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_microscopic_lab FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_microscopic_lab IS NOT NULL
          AND q.embedding_microscopic_lab IS NOT NULL
        ORDER BY rs.embedding_microscopic_lab <=> q.embedding_microscopic_lab
        LIMIT %(top_k)s

2026-03-06 17:54:59,501 INFO sqlalchemy.engine.Engine [cached since 41.87s ago] {'species_id': 129, 'top_k': 60}
2026-03-06 17:54:59,505 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_ecological <=> q.embedding_ecological) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_ecological FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_ecological IS NOT NULL
          AND q.embedding_ecological IS NOT NULL
        ORDER BY rs.embedding_ecological <=> q.embedding_ecological
        LIMIT %(top_k)s

2026-03-06 17:54:59,506 INFO sqlalchemy.engine.Engine [cached since 41.87s ago] {'species_id': 129, 'top_k': 60}
2026-03-06 17:54:59,512 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_taxonomic <=> q.embedding_taxonomic) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_taxonomic FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_taxonomic IS NOT NULL
          AND q.embedding_taxonomic IS NOT NULL
        ORDER BY rs.embedding_taxonomic <=> q.embedding_taxonomic
        LIMIT %(top_k)s

2026-03-06 17:54:59,514 INFO sqlalchemy.engine.Engine [cached since 41.88s ago] {'species_id': 129, 'top_k': 60}
2026-03-06 17:54:59,520 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:54:59,521 INFO sqlalchemy.engine.Engine [cached since 41.88s ago] {'pk_1': 117}
2026-03-06 17:54:59,532 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:54:59,534 INFO sqlalchemy.engine.Engine [cached since 41.89s ago] {'pk_1': 118}
2026-03-06 17:54:59,537 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:54:59,537 INFO sqlalchemy.engine.Engine [cached since 41.9s ago] {'pk_1': 119}
2026-03-06 17:54:59,541 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:54:59,542 INFO sqlalchemy.engine.Engine [cached since 41.9s ago] {'pk_1': 120}
2026-03-06 17:54:59,546 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:54:59,547 INFO sqlalchemy.engine.Engine [cached since 41.91s ago] {'pk_1': 121}
2026-03-06 17:54:59,554 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:54:59,555 INFO sqlalchemy.engine.Engine [cached since 41.91s ago] {'pk_1': 122}
2026-03-06 17:54:59,654 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:54:59,655 INFO sqlalchemy.engine.Engine [cached since 42.01s ago] {'pk_1': 123}

Error querying Cortinarius Seriocybe: Species not found: 'Cortinarius Seriocybe'

2026-03-06 17:55:00,316 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.scientific_name ILIKE %(scientific_name_1)s
 LIMIT %(param_1)s
2026-03-06 17:55:00,317 INFO sqlalchemy.engine.Engine [cached since 42.73s ago] {'scientific_name_1': 'Russula emetica', 'param_1': 1}
2026-03-06 17:55:00,323 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_macro_visual <=> q.embedding_macro_visual) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_macro_visual FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_macro_visual IS NOT NULL
          AND q.embedding_macro_visual IS NOT NULL
        ORDER BY rs.embedding_macro_visual <=> q.embedding_macro_visual
        LIMIT %(top_k)s

2026-03-06 17:55:00,323 INFO sqlalchemy.engine.Engine [cached since 42.71s ago] {'species_id': 155, 'top_k': 60}
2026-03-06 17:55:00,326 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_structural <=> q.embedding_structural) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_structural FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_structural IS NOT NULL
          AND q.embedding_structural IS NOT NULL
        ORDER BY rs.embedding_structural <=> q.embedding_structural
        LIMIT %(top_k)s

2026-03-06 17:55:00,327 INFO sqlalchemy.engine.Engine [cached since 42.71s ago] {'species_id': 155, 'top_k': 60}
2026-03-06 17:55:00,330 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_flesh_sensory <=> q.embedding_flesh_sensory) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_flesh_sensory FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_flesh_sensory IS NOT NULL
          AND q.embedding_flesh_sensory IS NOT NULL
        ORDER BY rs.embedding_flesh_sensory <=> q.embedding_flesh_sensory
        LIMIT %(top_k)s

2026-03-06 17:55:00,331 INFO sqlalchemy.engine.Engine [cached since 42.71s ago] {'species_id': 155, 'top_k': 60}
2026-03-06 17:55:00,339 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_microscopic_lab <=> q.embedding_microscopic_lab) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_microscopic_lab FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_microscopic_lab IS NOT NULL
          AND q.embedding_microscopic_lab IS NOT NULL
        ORDER BY rs.embedding_microscopic_lab <=> q.embedding_microscopic_lab
        LIMIT %(top_k)s

2026-03-06 17:55:00,358 INFO sqlalchemy.engine.Engine [cached since 42.73s ago] {'species_id': 155, 'top_k': 60}
2026-03-06 17:55:00,362 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_ecological <=> q.embedding_ecological) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_ecological FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_ecological IS NOT NULL
          AND q.embedding_ecological IS NOT NULL
        ORDER BY rs.embedding_ecological <=> q.embedding_ecological
        LIMIT %(top_k)s

2026-03-06 17:55:00,362 INFO sqlalchemy.engine.Engine [cached since 42.73s ago] {'species_id': 155, 'top_k': 60}
2026-03-06 17:55:00,365 INFO sqlalchemy.engine.Engine
        SELECT rs.id, rs.scientific_name,
               1 - (rs.embedding_taxonomic <=> q.embedding_taxonomic) AS similarity
        FROM reconciled_species rs,
             (SELECT embedding_taxonomic FROM reconciled_species WHERE id = %(species_id)s) AS q
        WHERE rs.id != %(species_id)s
          AND rs.embedding_taxonomic IS NOT NULL
          AND q.embedding_taxonomic IS NOT NULL
        ORDER BY rs.embedding_taxonomic <=> q.embedding_taxonomic
        LIMIT %(top_k)s

2026-03-06 17:55:00,365 INFO sqlalchemy.engine.Engine [cached since 42.73s ago] {'species_id': 155, 'top_k': 60}
2026-03-06 17:55:00,369 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:55:00,369 INFO sqlalchemy.engine.Engine [cached since 42.73s ago] {'pk_1': 117}
2026-03-06 17:55:00,373 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:55:00,374 INFO sqlalchemy.engine.Engine [cached since 42.73s ago] {'pk_1': 118}
2026-03-06 17:55:00,377 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:55:00,378 INFO sqlalchemy.engine.Engine [cached since 42.74s ago] {'pk_1': 119}
2026-03-06 17:55:00,381 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:55:00,382 INFO sqlalchemy.engine.Engine [cached since 42.74s ago] {'pk_1': 120}
2026-03-06 17:55:00,387 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:55:00,388 INFO sqlalchemy.engine.Engine [cached since 42.75s ago] {'pk_1': 121}
2026-03-06 17:55:00,394 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:55:00,394 INFO sqlalchemy.engine.Engine [cached since 42.75s ago] {'pk_1': 122}
2026-03-06 17:55:00,411 INFO sqlalchemy.engine.Engine SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.id = %(pk_1)s
2026-03-06 17:55:00,411 INFO sqlalchemy.engine.Engine [cached since 42.77s ago] {'pk_1': 123}

In [3]:
# Recall@K summary
for k in [1, 3, 5]:
    print(f"Recall@{k}: {result.hits_at(k)}/{result.total} = {result.recall_at(k):.1%}")

if result.errors:
    print(f"\nErrors (species not found / missing embeddings): {result.errors}")

Recall@1: 11/62 = 17.7%
Recall@3: 19/62 = 30.6%
Recall@5: 23/62 = 37.1%

Errors (species not found / missing embeddings): 2

In [4]:
# Log to MLflow
stats = dataset_stats(session)
ok = log_eval_to_mlflow(result, run_name=None, dataset_params=stats)
if ok:
    print("Logged to MLflow (experiment: eval_retrieval). View at http://localhost:5000")
else:
    print("MLflow logging skipped (service unavailable).")

2026-03-06 17:55:02,029 INFO sqlalchemy.engine.Engine SELECT count(*) AS count_1
FROM (SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species) AS anon_1
2026-03-06 17:55:02,031 INFO sqlalchemy.engine.Engine [generated in 0.00144s] {}
2026-03-06 17:55:02,041 INFO sqlalchemy.engine.Engine SELECT count(*) AS count_1
FROM (SELECT reconciled_species.id AS reconciled_species_id, reconciled_species.scientific_name AS reconciled_species_scientific_name, reconciled_species.common_names AS reconciled_species_common_names, reconciled_species.family AS reconciled_species_family, reconciled_species.genus AS reconciled_species_genus, reconciled_species.features_json AS reconciled_species_features_json, reconciled_species.edibility AS reconciled_species_edibility, reconciled_species.known_toxins AS reconciled_species_known_toxins, reconciled_species.known_lookalikes AS reconciled_species_known_lookalikes, reconciled_species.reconciliation_confidence AS reconciled_species_reconciliation_confidence, reconciled_species.needs_review AS reconciled_species_needs_review, reconciled_species.review_notes AS reconciled_species_review_notes, reconciled_species.human_overrides AS reconciled_species_human_overrides, reconciled_species.reconciled_at AS reconciled_species_reconciled_at, reconciled_species.source_count AS reconciled_species_source_count, reconciled_species.overall_body_form AS reconciled_species_overall_body_form, reconciled_species.embedding_macro_visual AS reconciled_species_embedding_macro_visual, reconciled_species.embedding_structural AS reconciled_species_embedding_structural, reconciled_species.embedding_flesh_sensory AS reconciled_species_embedding_flesh_sensory, reconciled_species.embedding_microscopic_lab AS reconciled_species_embedding_microscopic_lab, reconciled_species.embedding_ecological AS reconciled_species_embedding_ecological, reconciled_species.embedding_taxonomic AS reconciled_species_embedding_taxonomic, reconciled_species.embedded_at AS reconciled_species_embedded_at
FROM reconciled_species
WHERE reconciled_species.embedding_macro_visual IS NOT NULL) AS anon_1
2026-03-06 17:55:02,041 INFO sqlalchemy.engine.Engine [generated in 0.00048s] {}
2026-03-06 17:55:02,043 INFO sqlalchemy.engine.Engine SELECT count(*) AS count_1
FROM (SELECT ground_truth_pairs.id AS ground_truth_pairs_id, ground_truth_pairs.species_a AS ground_truth_pairs_species_a, ground_truth_pairs.species_b AS ground_truth_pairs_species_b, ground_truth_pairs.danger_note AS ground_truth_pairs_danger_note, ground_truth_pairs.source AS ground_truth_pairs_source, ground_truth_pairs.notes AS ground_truth_pairs_notes
FROM ground_truth_pairs) AS anon_1
2026-03-06 17:55:02,044 INFO sqlalchemy.engine.Engine [generated in 0.00031s] {}

/Users/aless/Desktop/Projects/mushroom-ai/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

🏃 View run overjoyed-loon-567 at: http://localhost:5000/#/experiments/1/runs/a01aba82fac741228a1a52186682311f
🧪 View experiment at: http://localhost:5000/#/experiments/1
Logged to MLflow (experiment: eval_retrieval). View at http://localhost:5000

In [5]:
# Hits — successful retrievals sorted by rank
hits = [r for r in result.pair_results if r.rank is not None]
df_hits = pd.DataFrame([vars(r) for r in hits]).sort_values("rank")
sim_cols = ["query", "target", "rank", "sim_overall",
            "sim_macro_visual", "sim_structural", "sim_flesh_sensory",
            "sim_microscopic_lab", "sim_ecological", "sim_taxonomic", "sim_numeric"]
display(df_hits[[c for c in sim_cols if c in df_hits.columns]].round(3))

,query,target,rank,sim_overall,sim_macro_visual,sim_structural,sim_flesh_sensory,sim_microscopic_lab,sim_ecological,sim_taxonomic,sim_numeric
11,Amanita pantherina,Amanita rubescens,1,0.867,0.964,0.869,0.817,0.610,0.970,0.825,0.596
20,Hypholoma fasciculare,Hypholoma capnoides,1,0.879,0.910,0.916,0.784,0.605,0.947,0.826,0.800
4,Boletus edulis,Tylopilus felleus,1,0.856,0.933,0.915,0.886,0.781,0.924,0.854,0.511
5,Tylopilus felleus,Boletus edulis,1,0.856,0.933,0.915,0.886,0.781,0.924,0.854,0.511
16,Macrolepiota procera,Macrolepiota rhacodes,1,0.808,0.926,0.913,0.940,0.552,0.844,0.858,0.329
15,Coprinopsis atramentaria,Coprinus comatus,1,0.831,0.953,0.892,0.826,0.984,0.847,0.867,0.378
9,Galerina marginata,Kuehneromyces mutabilis,1,0.847,0.902,0.868,0.900,0.848,0.980,0.763,0.532
21,Hypholoma capnoides,Hypholoma fasciculare,1,0.879,0.910,0.916,0.784,0.605,0.947,0.826,0.800
12,Lactarius deliciosus,Lactarius torminosus,1,0.824,0.917,0.759,0.826,0.911,0.896,0.851,0.552
13,Lactarius torminosus,Lactarius deliciosus,1,0.824,0.917,0.759,0.826,0.911,0.896,0.851,0.552
14,Coprinus comatus,Coprinopsis atramentaria,1,0.831,0.953,0.892,0.826,0.984,0.847,0.867,0.378
19,Clitocybe dealbata,Clitocybe gibba,2,0.677,0.823,0.690,0.589,0.312,0.810,0.788,0.212
3,Agaricus xanthodermus,Agaricus campestris,2,0.848,0.921,0.914,0.971,0.983,0.822,0.871,0.520
8,Kuehneromyces mutabilis,Galerina marginata,2,0.847,0.902,0.868,0.900,0.848,0.980,0.763,0.532
10,Amanita rubescens,Amanita pantherina,2,0.867,0.964,0.869,0.817,0.610,0.970,0.825,0.596
0,Amanita caesarea,Amanita muscaria,3,0.836,0.907,0.853,0.791,0.649,0.949,0.742,0.602
6,Macrolepiota procera,Chlorophyllum molybdites,3,0.800,0.924,0.879,0.863,0.546,0.859,0.784,0.362
2,Agaricus campestris,Agaricus xanthodermus,3,0.848,0.921,0.914,0.971,0.983,0.822,0.871,0.520
22,Russula Vesca,Russula emetica,3,0.817,0.908,0.874,0.899,0.385,0.980,0.856,0.374
17,Macrolepiota rhacodes,Macrolepiota procera,4,0.808,0.926,0.913,0.940,0.552,0.844,0.858,0.329
1,Amanita muscaria,Amanita caesarea,4,0.836,0.907,0.853,0.791,0.649,0.949,0.742,0.602
18,Psilocybe cubensis,Galerina marginata,5,0.762,0.884,0.877,0.826,0.859,0.858,0.509,0.247
7,Chlorophyllum molybdites,Macrolepiota procera,5,0.800,0.924,0.879,0.863,0.546,0.859,0.784,0.362

In [6]:
# Misses — target not found in top-K
misses = [r for r in result.pair_results if r.rank is None]
df_misses = pd.DataFrame([vars(r) for r in misses])
display(df_misses[["query", "target", "error"]])

,query,target,error
0,Amanita caesarea,Amanita phalloides,None
1,Amanita phalloides,Amanita caesarea,None
2,Agaricus campestris,Amanita phalloides,None
3,Amanita phalloides,Agaricus campestris,None
4,Cantharellus cibarius,Omphalotus olearius,None
5,Omphalotus olearius,Cantharellus cibarius,None
6,Cantharellus cibarius,Hygrophoropsis aurantiaca,None
7,Hygrophoropsis aurantiaca,Cantharellus cibarius,None
8,Morchella esculenta,Gyromitra esculenta,None
9,Gyromitra esculenta,Morchella esculenta,None
10,Armillaria mellea,Galerina marginata,None
11,Galerina marginata,Armillaria mellea,None
12,Russula virescens,Amanita phalloides,None
13,Amanita phalloides,Russula virescens,None
14,Calvatia gigantea,Amanita phalloides,None
15,Amanita phalloides,Calvatia gigantea,None
16,Amanita phalloides,Volvariella volvacea,None
17,Volvariella volvacea,Amanita phalloides,None
18,Amanita verna,Agaricus campestris,None
19,Agaricus campestris,Amanita verna,None
20,Amanita citrina,Armillaria mellea,None
21,Armillaria mellea,Amanita citrina,None
22,Armillaria mellea,Hypholoma fasciculare,None
23,Hypholoma fasciculare,Armillaria mellea,None
24,Armillaria mellea,Hypholoma sublateritium,None
25,Hypholoma sublateritium,Armillaria mellea,None
26,Macrolepiota procera,Lepiota,None
27,Lepiota,Macrolepiota procera,None
28,Coprinus comatus,Amanita virosa,None
29,Amanita virosa,Coprinus comatus,None
30,Amanita phalloides,Amanita ocreata,None
31,Amanita ocreata,Amanita phalloides,None
32,Galerina marginata,Psilocybe cubensis,None
33,Clitocybe gibba,Clitocybe dealbata,None
34,Laccaria amethystina,Cortinarius Seriocybe,None
35,Cortinarius Seriocybe,Laccaria amethystina,Species not found: 'Cortinarius Seriocybe'
36,Cortinarius Violaceus,Cortinarius Seriocybe,None
37,Cortinarius Seriocybe,Cortinarius Violaceus,Species not found: 'Cortinarius Seriocybe'
38,Russula emetica,Russula Vesca,None

In [ ]:
# Weight sweep: precompute once, rescore with 200 random configs
from evaluation.sweep import sweep_weights

sweep_results = sweep_weights(session, pairs, n_configs=200, seed=42)

df_sweep = pd.DataFrame([
    {
        "R@1": r.recall_at[1],
        "R@3": r.recall_at[3],
        "R@5": r.recall_at[5],
        **{f: r.weights[f] for f in r.weights if f != "body_form_filter"},
        "body_form_filter": r.weights["body_form_filter"],
    }
    for r in sweep_results
])
print(f"Swept {len(sweep_results)} configs. Top 20:")
display(df_sweep.head(20).round(4))